const popup = document.querySelector('.popup'); // основной попап
const popupElement = document.querySelector(".popup_type_profile"); // доп попап профиля !!!!
const popupCardElement = document.querySelector(".popup_type_card"); // доп попап Новое место
const popupImageElement = document.querySelector(".popup__open-image"); // доп попап открытие фото
const popupCloseButtonElement = document.querySelector(".popup__close"); // кнопка закрытия попапа !!!!
const popupOpenButtonElement = document.querySelector(".profile__edit-button"); // кнопка открытия профиля !!!!
const popupCardOpenButtonElement = document.querySelector(".profile__add-button"); //  кнопка открытия Новое место
const formElement = document.querySelector(".popup__form"); // форма профиля
const formCardElement = document.querySelector(".popup__form_type_card"); //форма новое место
const nameInputElement = document.querySelector(".popup__form-input_status_name"); //имя
const jobInputElement = document.querySelector(".popup__form-input_status_job"); //профессия
const profileNameElement = document.querySelector(".profile__title");//имя в профиле
const profileJobElement = document.querySelector(".profile__subtitle"); //профессия в профиле
const list = document.querySelector(".element"); //ul
const popupImage = document.querySelector(".popup__image"); //картинка в попапе фото
const popuptitle = document.querySelector(".popup__image-title"); //надпись в попапе фото
